### ISSUE TITLE
Book lookup with empty title returns no response

### ISSUE THREAD

**Issue by STommydx** [dazzling-sky/comp4111-project#29]
**Describe the bug**
Book lookup with empty title returns no response

**To Reproduce**
1. Login as usual
2. Add a book
```json
{
            "Title": "# Book!",
            "Author": "Author",
            "Publisher": "Publisher",
            "Year": "2028"
}
```
3. Search book containing empty title
`GET localhost:8080/BookManagementService/books?title=&token={{token}}`

**Expected behavior**
`200 OK` with the book returned
```json
{
    "FoundBooks": 1,
    "Results": [
        {
            "Title": "# Book!",
            "Author": "Author",
            "Publisher": "Publisher",
            "Year": "2028"
        }
    ]
}
```

**What actually happens**
The server returns no response, throwing the following error in console
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at LibraryManagementService_Async.Utils.URIparser.getQueryParams(URIparser.java:58)
        at LibraryManagementService_Async.Utils.URIparser.getToken(URIparser.java:74)
        at LibraryManagementService_Async.Operations.BookManagement.lookBooks(BookManagement.java:99)
        at LibraryManagementService_Async.Handlers.POSTHandler.handleInternal(POSTHandler.java:66)
        at LibraryManagementService_Async.Handlers.Handler.handle(Handler.java:35)
        at LibraryManagementService_Async.Handlers.Handler.handle(Handler.java:13)
        at org.apache.http.nio.protocol.HttpAsyncService.responseReady(HttpAsyncService.java:480)
        at org.apache.http.impl.nio.DefaultNHttpServerConnection.produceOutput(DefaultNHttpServerConnection.java:306)
        at org.apache.http.impl.nio.DefaultHttpServerIODispatch.onOutputReady(DefaultHttpServerIODispatch.java:248)
        at org.apache.http.impl.nio.DefaultHttpServerIODispatch.onOutputReady(DefaultHttpServerIODispatch.java:57)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.outputReady(AbstractIODispatch.java:145)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.writable(BaseIOReactor.java:187)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:341)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by comp4111ta** [comment]
I encountered this one, too.
